# Generated by Django 3.1.2 on 2020-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201004_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
